FROM gradle:jdk11 as builder

COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle runtime

FROM debian:stable-slim AS libz

FROM gcr.io/distroless/base-debian10

EXPOSE 8080
WORKDIR /app
COPY --from=builder /home/gradle/src/build/image /app
COPY --from=libz /lib/x86_64-linux-gnu/libz.so.1 /lib/x86_64-linux-gnu/libz.so.1
ENTRYPOINT ["/app/bin/java"]
CMD ["-classpath", "/app/lib/*", "org.springframework.boot.loader.JarLauncher"]