FROM gradle:jdk11 as builder

COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
RUN gradle build

FROM gcr.io/distroless/java:11

EXPOSE 8080
WORKDIR /app
COPY --from=builder /home/gradle/src/build/libs/*.jar ./app.jar
ENTRYPOINT ["java", "-Xmx128M", "-XX:+FlightRecorder", "-XX:+PrintFlagsFinal", "-jar", "app.jar"]