name: frontapi small

on:
  push:
    branches: [ main ]
    paths:
    - 'src/frontapi/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: frontapi
  IMAGE_TAG: small-latest

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src/frontapi'
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew buildImage
    - name: Add Docker image tag
      run: |
        docker tag frontapi:latest ${IMAGE_NAME}:${IMAGE_TAG}
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        format: table
        exit-code: '1'
        ignore-unfixed: true
        vuln-type: 'os,library'
        severity: 'CRITICAL,HIGH'
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push the Docker image to Docker Hub
      env:
        DOCKER_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      run: |
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG}
        docker push ${DOCKER_USER}/${IMAGE_NAME}:${IMAGE_TAG}
