name: frontapi large

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  IMAGE_NAME: large/frontapi
  IMAGE_TAG: latest

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src/frontapi'
    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile.large
        push: true
        tags: crystalline407/large/frontapi:latest
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
